#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Nothing is written to a .env: the only values this wizard captures are
# CI secrets, and they go straight to GitHub.
TOTAL_STAGES=8
REPO="convalesce/emit"
PACKAGES=(convalesce-emit convalesce-emit-airflow convalesce-emit-dagster convalesce-emit-prefect convalesce-emit-gx)
VERSION="0.1.0"

banner "emit: first release"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "TestPyPI: register the workflow as a trusted publisher"
say "Trusted publishing means no API token: PyPI trusts the GitHub workflow itself."
say "Each of the five names needs a pending publisher, filled in identically"
say "except for the project name."
open_url "https://test.pypi.org/manage/account/publishing/"
step "Sign in (or create an account) on test.pypi.org, then scroll to 'Add a new pending publisher'."
say ""
say "  For each project name below, fill the GitHub form with:"
note "    Owner:            convalesce"
note "    Repository name:  emit"
note "    Workflow name:    publish.yml"
note "    Environment name: testpypi"
say ""
for p in "${PACKAGES[@]}"; do step "PyPI Project Name: $p   → Add"; done
pause "Press Enter once all five pending publishers are listed."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Rehearse: upload to TestPyPI from GitHub Actions"
say "This runs the real publish workflow against the test index. It claims"
say "nothing on PyPI and touches nothing else."
if confirm "Start the rehearsal now?"; then
  gh workflow run publish.yml --repo "$REPO" --ref main -f rehearse=true
  say "Waiting for the run to register…"
  sleep 8
  run_id=$(gh run list --repo "$REPO" --workflow publish.yml --limit 1 --json databaseId -q '.[0].databaseId')
  say "Watching run $run_id (Ctrl-C stops watching, not the run)."
  gh run watch --repo "$REPO" "$run_id" --exit-status && say "✓ rehearsal passed" || warn "the rehearsal failed; read the run before going on"
  open_url "https://test.pypi.org/project/convalesce-emit/"
  step "Check the five projects exist on test.pypi.org with version $VERSION."
  pause
else
  SKIPPED+=("TestPyPI rehearsal (Actions → publish → Run workflow, 'Upload to TestPyPI' ticked)")
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "PyPI: register the workflow as a trusted publisher"
say "Same form as TestPyPI, on the real index, with the 'pypi' environment."
say "The first upload from the tag will claim each name."
open_url "https://pypi.org/manage/account/publishing/"
step "Sign in on pypi.org, then scroll to 'Add a new pending publisher'."
say ""
note "    Owner:            convalesce"
note "    Repository name:  emit"
note "    Workflow name:    publish.yml"
note "    Environment name: pypi"
say ""
for p in "${PACKAGES[@]}"; do step "PyPI Project Name: $p   → Add"; done
pause "Press Enter once all five pending publishers are listed."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Maven Central: verify the io.convalesce namespace"
say "Central publishes only into a namespace you have proven you own. For a"
say "reverse-domain namespace that is a DNS TXT record on convalesce.io."
warn "Stages 4 to 6 can be skipped: a tag then publishes to PyPI only, and the"
warn "Central job stops with a notice instead of failing. Re-run later to add it."
if confirm "Set up Maven Central now?"; then
  CENTRAL=1
  open_url "https://central.sonatype.com/publishing/namespaces"
  step "Sign in (GitHub sign-in works), then 'Add Namespace' → io.convalesce."
  step "The portal shows a verification key. Add a TXT record on convalesce.io whose value is that key."
  step "Back on the portal, click 'Verify Namespace'. DNS can take a few minutes."
  pause "Press Enter once the namespace shows as verified."
else
  CENTRAL=0
  SKIPPED+=("Maven Central namespace, token and signing key (re-run this wizard)")
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Maven Central: a user token for the workflow"
if (( CENTRAL )); then
  say "The workflow deploys with a portal user token, never your login."
  open_url "https://central.sonatype.com/account"
  step "Click 'Generate User Token' and confirm. It shows a username and a password once."
  ask CENTRAL_USERNAME "Paste the token username:"
  ask_secret CENTRAL_PASSWORD "Paste the token password:"
  set_secret CENTRAL_USERNAME "$CENTRAL_USERNAME"
  set_secret CENTRAL_PASSWORD "$CENTRAL_PASSWORD"
else
  note "skipped with stage 4"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Maven Central: a signing key"
if (( CENTRAL )); then
  say "Central rejects unsigned jars. The workflow signs with a key it reads"
  say "from a secret; the public half must be on a key server."
  if confirm "Generate a new key now with gpg?"; then
    say "gpg will ask for a name, an email and a passphrase. Use a release identity,"
    say "e.g. 'Convalesce Release', and remember the passphrase."
    gpg --full-generate-key
  fi
  say ""
  gpg --list-secret-keys --keyid-format=long | sed 's/^/    /'
  ask KEY_ID "Key id to use (the hex after 'sec   rsa4096/'):"
  ask_secret SIGNING_PASSWORD "Its passphrase:"
  say "Publishing the public key…"
  gpg --keyserver keyserver.ubuntu.com --send-keys "$KEY_ID" && say "✓ sent to keyserver.ubuntu.com" || warn "could not reach the key server; run: gpg --keyserver keyserver.ubuntu.com --send-keys $KEY_ID"
  SIGNING_KEY=$(gpg --armor --export-secret-keys "$KEY_ID")
  set_secret SIGNING_KEY "$SIGNING_KEY"
  set_secret SIGNING_PASSWORD "$SIGNING_PASSWORD"
else
  note "skipped with stage 4"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Tag v$VERSION and publish"
say "The tag is the release. The workflow checks every declared version"
say "against it, uploads to PyPI, deploys to Central if configured, and"
say "creates the GitHub release."
git -C "$(git rev-parse --show-toplevel)" fetch -q origin main
if [[ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]]; then
  warn "HEAD is not origin/main; the tag must point at the reviewed main."
fi
if confirm "Create and push the tag v$VERSION from origin/main?"; then
  git tag "v$VERSION" origin/main
  git push origin "v$VERSION"
  say "Waiting for the run to register…"
  sleep 8
  run_id=$(gh run list --repo "$REPO" --workflow publish.yml --limit 1 --json databaseId -q '.[0].databaseId')
  say "Watching run $run_id…"
  gh run watch --repo "$REPO" "$run_id" --exit-status && say "✓ published" || warn "the release run failed; read it before retagging"
  open_url "https://pypi.org/project/convalesce-emit/"
else
  SKIPPED+=("tag: git tag v$VERSION origin/main && git push origin v$VERSION")
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Maven Central: release the staged deployment"
if (( CENTRAL )); then
  say "A deployment lands in staging. Central validates the POM, sources,"
  say "javadoc and signatures on the way in; releasing it is one click."
  open_url "https://central.sonatype.com/publishing/deployments"
  step "Find the io.convalesce deployment for $VERSION and click 'Publish'."
  pause "Press Enter once it shows as published."
else
  note "skipped with stage 4"
fi

finish
